---
# Update all packages to the latest version
- name: apt-get update
  apt: update_cache=yes
  become: yes
  become_user: root

- apt: upgrade=dist
  become: yes
  become_user: root

- name: be sure ntp is installed
  apt: name=ntp state=installed
  become_user: 'root'
  become: yes
  tags: ntp

- name: be sure ntp is running and enabled
  service: name=ntp state=running enabled=yes
  become_user: 'root'
  become: yes
  tags: ntp

- include: docker.yml
